/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.sisong.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import ucr.ac.cr.sisong.model.Artist;

/**
 *
 * @author Dell E7490
 */
public class DataPanelArtist extends javax.swing.JPanel {

    /**
     * Creates new form DataPanelArtist
     */
    public DataPanelArtist() {
        initComponents();
        addCountry();
        addGenre();
    }
    
    //Metodo que se encarga de cargar el id en el label
    public void setLbIdArtist(int idArtist){
        this.lbIDARTIST.setText(String.valueOf(idArtist));
    }
    
    public String getTxtName()
    {
        return this.txtArtistName.getText();
    }
    
    
    
    //Obtener datos de la ventana y enviarlos a guardar 
    public Artist getArtist(){
        Artist artist = new Artist( Integer.parseInt(this.lbIDARTIST.getText()), 
                this.txtArtistName.getText(), 
                this.cbCountry.getSelectedItem().toString(),
                this.cbMusicGenre.getSelectedItem().toString()); 
        
        
        return artist;
    }
    
    //Buscar en el registro, obtener y cargar los datos en los campos de la interfaz 
    public void setArtist(Artist artist){
        this.lbIDARTIST.setText(String.valueOf(artist.getIdArtist()));
        this.txtArtistName.setText(artist.getName());
        this.cbCountry.setSelectedItem(artist.getCountry());
        this.cbMusicGenre.setSelectedItem(artist.getMusicGenre());
    }
    
    public void clean(){
        this.lbIDARTIST.setText("");
        this.txtArtistName.setText("");
        this.cbCountry.setSelectedIndex(0);
        this.cbMusicGenre.setSelectedIndex(0);
    }
    
    public void addGenre(){
        this.cbMusicGenre.setModel(new DefaultComboBoxModel<>(new String[] {"Select option", "Rock", "Clasica", "Pop", "Salsa", "Cumbia", "Reggaeton", "Reggae"}));     
    }
    
    public void addCountry(){
        this.cbCountry.setModel(new DefaultComboBoxModel<>(new String[] {"Select option", "Jamaica", "Colombia", "Argentina", "USA", "Mexico", "Corea", "Alemania", "Brasil"}));     
    }
    
    public void setCbArtist(String [] idArtist){
        DefaultComboBoxModel model = new DefaultComboBoxModel(idArtist);
        model.insertElementAt("Selected option", 0);
        this.cbArtist.setModel(model);
    }
    
    
    public void listenCombo(ActionListener controller){
        this.cbArtist.addActionListener(controller);
    }
    
    //Obtengo donde le di click
    public String getCbArtist(){
        return this.cbArtist.getSelectedItem().toString();
    }
    
    public void setEditCbCombo(boolean state){
        this.cbArtist.setEnabled(state);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbMusicGenre = new javax.swing.JComboBox<>();
        cbCountry = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lbIDARTIST = new javax.swing.JLabel();
        cbArtist = new javax.swing.JComboBox<>();
        txtArtistName = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 153));
        jLabel1.setText("Artist record");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 153));
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 153));
        jLabel3.setText("Country:");

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 153));
        jLabel4.setText("Music genre:");

        cbMusicGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMusicGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMusicGenreActionPerformed(evt);
            }
        });

        cbCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 153));
        jLabel5.setText("Id Artist");

        lbIDARTIST.setBackground(new java.awt.Color(255, 204, 204));
        lbIDARTIST.setForeground(new java.awt.Color(255, 204, 255));

        cbArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbArtistActionPerformed(evt);
            }
        });

        txtArtistName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtistNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cbMusicGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbIDARTIST, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(txtArtistName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(92, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbArtist)
                        .addComponent(jLabel5))
                    .addComponent(lbIDARTIST, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtArtistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbMusicGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbMusicGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMusicGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMusicGenreActionPerformed

    private void cbArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbArtistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbArtistActionPerformed

    private void txtArtistNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtistNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArtistNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbArtist;
    private javax.swing.JComboBox<String> cbCountry;
    private javax.swing.JComboBox<String> cbMusicGenre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbIDARTIST;
    private javax.swing.JTextField txtArtistName;
    // End of variables declaration//GEN-END:variables
}
