/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.sisong.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell E7490
 */
public class GUIArtist extends javax.swing.JFrame {

    /**
     * Creates new form GUIArtist
     */
    public GUIArtist() {
        initComponents();
    }

    //Metodo que retorna el panel data 
    public DataPanelArtist getDataPanelArtist(){
        return this.dataPanelArtist7;
    }
    
    //Metodo que retorna el panel de botones 
    public ButtonsPanel getButtonPanel(){
        return this.buttonsPanel1;
    }
    
    public static void setMessage(String msj){
        JOptionPane.showMessageDialog(null, msj);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataPanelArtist2 = new ucr.ac.cr.sisong.view.DataPanelArtist();
        dataPanelArtist1 = new ucr.ac.cr.sisong.view.DataPanelArtist();
        dataPanelArtist3 = new ucr.ac.cr.sisong.view.DataPanelArtist();
        dataPanelArtist4 = new ucr.ac.cr.sisong.view.DataPanelArtist();
        dataPanelArtist5 = new ucr.ac.cr.sisong.view.DataPanelArtist();
        dataPanelArtist6 = new ucr.ac.cr.sisong.view.DataPanelArtist();
        buttonsPanel1 = new ucr.ac.cr.sisong.view.ButtonsPanel();
        dataPanelArtist7 = new ucr.ac.cr.sisong.view.DataPanelArtist();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(dataPanelArtist7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataPanelArtist7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(buttonsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.sisong.view.ButtonsPanel buttonsPanel1;
    private ucr.ac.cr.sisong.view.DataPanelArtist dataPanelArtist1;
    private ucr.ac.cr.sisong.view.DataPanelArtist dataPanelArtist2;
    private ucr.ac.cr.sisong.view.DataPanelArtist dataPanelArtist3;
    private ucr.ac.cr.sisong.view.DataPanelArtist dataPanelArtist4;
    private ucr.ac.cr.sisong.view.DataPanelArtist dataPanelArtist5;
    private ucr.ac.cr.sisong.view.DataPanelArtist dataPanelArtist6;
    private ucr.ac.cr.sisong.view.DataPanelArtist dataPanelArtist7;
    // End of variables declaration//GEN-END:variables
}
