/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.sisong.view;

import java.awt.event.ActionListener;

/**
 *
 * @author Dell E7490
 */
public class GUIMain extends javax.swing.JFrame {

    /**
     * Creates new form GUIMain
     */
    public GUIMain() {
        initComponents();
    }
    
    public void listen(ActionListener controller){
        
        this.jmiExit.addActionListener(controller);
        this.jmiCredits.addActionListener(controller);
        this.jmiSongs.addActionListener(controller);
        this.jmiArtists.addActionListener(controller);
        this.jmiAlbums.addActionListener(controller);
        this.itmTables.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jmiExit = new javax.swing.JMenuItem();
        jmiCredits = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiSongs = new javax.swing.JMenuItem();
        jmiArtists = new javax.swing.JMenuItem();
        jmiAlbums = new javax.swing.JMenuItem();
        itmTables = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("File");

        jmiExit.setText("Exit");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jMenu3.add(jmiExit);

        jmiCredits.setActionCommand("Credits");
        jmiCredits.setLabel("Credits");
        jMenu3.add(jmiCredits);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Modules");

        jmiSongs.setText("Songs");
        jmiSongs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSongsActionPerformed(evt);
            }
        });
        jMenu4.add(jmiSongs);

        jmiArtists.setText("Artists");
        jMenu4.add(jmiArtists);

        jmiAlbums.setText("Albums");
        jMenu4.add(jmiAlbums);

        itmTables.setText("Tables");
        itmTables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmTablesActionPerformed(evt);
            }
        });
        jMenu4.add(itmTables);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiExitActionPerformed

    private void jmiSongsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSongsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiSongsActionPerformed

    private void itmTablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmTablesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmTablesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmTables;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jmiAlbums;
    private javax.swing.JMenuItem jmiArtists;
    private javax.swing.JMenuItem jmiCredits;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiSongs;
    // End of variables declaration//GEN-END:variables
}
